### ISSUE TITLE
Anaconda3 の最新版の環境で leda-votable-to-galaxy.py が動作しない

### ISSUE THREAD

**Issue by rnanba** [rnanba/GalaxyAnnotator#13]
Anaconda3-2023.07-2 をインストールした環境で `leda-votable-to-galaxy.py` が「ValueError: Use of `bounds` is incompatible with 'method=Brent'.」で異常終了する。

```
Traceback (most recent call last):
  File "/home/rna/Projects/GalaxyAnnotator/leda-votable-to-galaxy.py", line 100, in <module>
    z = z_at_value(cosmo.luminosity_distance, ld)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rna/anaconda3_2023/lib/python3.11/site-packages/astropy/cosmology/funcs.py", line 358, in z_at_value
    zs[...] = _z_at_scalar_value(func, fv * unit, zmin=zmn, zmax=zmx,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rna/anaconda3_2023/lib/python3.11/site-packages/astropy/cosmology/funcs.py", line 79, in _z_at_scalar_value
    res = minimize_scalar(f, method=method, bounds=(zmin, zmax),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rna/anaconda3_2023/lib/python3.11/site-packages/scipy/optimize/_minimize.py", line 887, in minimize_scalar
    raise ValueError(message)
ValueError: Use of `bounds` is incompatible with 'method=Brent'.
```

**Comment by rnanba** [comment]
今年の1月に https://github.com/astropy/astropy/issues/14249 で scipy 1.10 以降と astropy の相性問題が報告され、astropy 5.2.1 で対応された現象と同じものと思われる。

Anaconda3-2023.07-2 環境で `conda list '(astropy|scipy)'` でモジュールのバージョンを確認すると以下の通りで相性問題が発生する組み合わせだった。
```
astropy  5.1  py311ha0d4635_0
scipy  1.10.1 py311hc76d9b0_1
```

astropy 5.2.1 以降は anaconda の本家チャンネルではまだリリースされていないので、scipy を 1.9.3 にダウングレードすることで解決した。

```
conda install scipy=1.9.3
```
