### ISSUE TITLE
galaxy.json で style を指定すると NameError になることがある

### ISSUE THREAD

**Issue by rnanba** [rnanba/GalaxyAnnotator#14]
v0.9.1 で以下のような galaxies.json を指定すると `NameError: name 's_label_position' is not defined. Did you mean: 'def_label_position'?` が発生してエラーで終了する。

## 例1

galaxies.json:
```json
{
  "galaxies": [
    {
      "name": "NGC4826",
      "al2000": 12.9454673,
      "de2000": 21.6821044,
      "pa": 114.0,
      "logd25": 2.022,
      "logr25": 0.295,
      "descs": [
        "1440万光年"
      ],
      "style": {
        "name": {
          "fill": "red"
        }
      }
    }
  ]
}
```
エラー:
```
Traceback (most recent call last):
  File "/archive/rna/tmp/GalaxyAnnotator/./galaxy-annotator.py", line 269, in <module>
    if not('text-anchor' in s['name']) and s_label_position:
                                           ^^^^^^^^^^^^^^^^
NameError: name 's_label_position' is not defined. Did you mean: 'def_label_position'?
```
## 例2

galaxies.json:
```json
{
  "galaxies": [
    {
      "name": "NGC4826",
      "al2000": 12.9454673,
      "de2000": 21.6821044,
      "pa": 114.0,
      "logd25": 2.022,
      "logr25": 0.295,
      "descs": [
        "1440万光年"
      ],
      "style": {
        "desc": [
          {
            "fill": "red"
          }
        ]
      }
    }
  ]
}
```
エラー:
```
Traceback (most recent call last):
  File "/archive/rna/tmp/GalaxyAnnotator/./galaxy-annotator.py", line 275, in <module>
    if not('text-anchor' in desc) and s_label_position:
                                      ^^^^^^^^^^^^^^^^
NameError: name 's_label_position' is not defined. Did you mean: 'def_label_position'?
```

**Comment by rnanba** [comment]
v0.9.2 で修正しました。
