### ISSUE TITLE
日本語Windows環境で galaxy-annotator.py がJSON読み込みエラー

### ISSUE THREAD

**Issue by rnanba** [rnanba/GalaxyAnnotator#5]
日本語Windowsで galaxy-annotator.py にサンプルの json ファイルを指定して実行すると以下のエラーが発生する。
```
Traceback (most recent call last):
  File ".\galaxy-annotator.py", line 20, in <module>
    galaxies = json.load(f)
  File "C:\Users\nanba\anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'cp932' codec can't decode byte 0x84 in position 212: illegal multibyte sequence
```

**Comment by rnanba** [comment]
Windowsの日本語環境ではデフォルトのロケールが cp932 (≒Shift_JIS)なので、デフォルトエンコーディングのままファイルを開くと utf-8 で読んでくれない模様。JSONは必ずutf-8なのでJSONの読み込みでは encoding='utf-8' を明示するようにします。
